- name: Install certbot dependencies
  apt:
    name: software-properties-common
    update_cache: true
- name: Install certbot repository
  apt_repository:
    repo: ppa:certbot/certbot
- name: Install certbot
  apt:
    name: python-certbot-nginx
    update_cache: true
- name: Install certificates
  command: certbot --nginx -n --agree-tos --expand --email {{ certbot_email }} --domains {{ certbot_domains|join(',') }} certonly
  tags:
    # certbot command is idempotent
    - skip_ansible_lint

- name: Ensure server(s) are restarted
  meta: flush_handlers

- name: Test domains
  uri:
    url: "{{ remote_check_url }}"
