---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    users:
      - afeld
      - allthesignals
      - andycochran
      - chriswhong
    former_users: []
  roles:
    - role: andrewsomething.do-agent
    - role: jnv.unattended-upgrades
  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
    - name: Restart Docker
      service:
        name: docker
        state: restarted
  tasks:
    - name: User management
      block:
        - name: Set up users
          include_tasks: tasks/user.yml
          loop: "{{ users }}"
        - name: Remove former users
          user:
            name: "{{ item }}"
            state: absent
          loop: "{{ former_users }}"
    - name: SSH configuration
      block:
        - name: Disallow root SSH access
          lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: ^PermitRootLogin
            line: PermitRootLogin no
          notify: Restart SSH
        - name: Disallow SSH authentication with password
          lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: ^PasswordAuthentication
            line: PasswordAuthentication no
          notify: Restart SSH
        # this helps ensure that you don't get locked out of the machine
        - fail:
            msg: No users are specified
          when: not users
        - name: Only allow specified users to SSH
          lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: ^AllowUsers
            line: AllowUsers {{ 'vagrant ' if ansible_user == 'vagrant' }}{{ users|join(' ') }}
          notify: Restart SSH
    - name: Copy in Docker config
      copy:
        src: files/docker-daemon.json
        dest: /etc/docker/daemon.json
      notify: Restart Docker
