version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    environment:
      - ANSIBLE_FORCE_COLOR: "True"
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: pipenv install
      - run:
          name: Install Ansible dependencies
          command: pipenv run ansible-galaxy install -p roles -r requirements.yml
      - run:
          name: Check syntax of Ansible playbooks
          command: pipenv run ansible-playbook --syntax-check playbooks/*.yml
      - run:
          name: Lint the Ansible playbooks
          command: pipenv run ansible-lint --exclude=roles playbooks/*.yml
      - run:
          name: Run the test playbook against all Droplets
          command: pipenv run ansible-playbook -i digital_ocean.py -l labs -u deployer playbooks/test.yml
      - run:
          name: Run the base playbook in check mode against all Droplets
          command: pipenv run ansible-playbook -i digital_ocean.py -l labs -u deployer -C playbooks/base.yml
workflows:
  version: 2
  build:
    jobs:
      - build
