version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: pipenv install
      - run:
          name: Install Ansible dependencies
          command: pipenv run ansible-galaxy install -p roles -r requirements.yml
      - run:
          name: Check syntax of Ansible playbooks
          command: pipenv run ansible-playbook --syntax-check playbooks/*.yml
      - run:
          name: Lint the Ansible playbooks
          command: pipenv run ansible-lint --exclude=roles playbooks/*.yml
workflows:
  version: 2
  build:
    jobs:
      - build
