version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: pipenv install
      - run:
          name: Install Ansible dependencies
          command: pipenv run ansible-galaxy install -p roles -r requirements.yml
      - run:
          name: Check syntax of Ansible playbooks
          command: pipenv run ansible-playbook --syntax-check playbooks/*.yml
      - run:
          name: Lint the Ansible playbooks
          command: pipenv run ansible-lint --exclude=roles playbooks/*.yml
      - run:
          name: Run the test playbook against all machines
          # redact IP addresses
          # https://gist.github.com/afeld/e53ac65e122ccd27547f2d2a54755f8b
          command: |
            pipenv run ansible-playbook -i digital_ocean.py -u deployer playbooks/test.yml | \
            sed -E 's/[0-9]+\.[0-9]+\.[0-9]+\.([0-9]+)/███.███.███.\1/g'
          environment:
            ANSIBLE_FORCE_COLOR: "True"
workflows:
  version: 2
  build:
    jobs:
      - build
