version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3
    steps:
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v2-{{ .Branch }}-
            - pip-packages-v2-
      - run:
          name: Install Python dependencies
          command: pipenv install
      - save_cache:
          paths:
            - ~/.local/share/virtualenvs
          key: pip-packages-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install Ansible dependencies
          command: pipenv run ansible-galaxy install -p roles/external -r requirements.yml
      - persist_to_workspace:
          root: .
          paths:
            - ./*

      - run:
          name: Check syntax of Ansible playbooks
          command: pipenv run ansible-playbook --syntax-check playbooks/*.yml
      - run:
          name: Lint the Ansible playbooks
          command: pipenv run ansible-lint --exclude=roles playbooks/*.yml
      - run:
          name: Run the test playbook against all Droplets
          command: pipenv run ansible-playbook -i digital_ocean.py -l labs -u deployer playbooks/test.yml
      - run:
          name: Run the base playbook in check mode against all Droplets
          command: pipenv run ansible-playbook -i digital_ocean.py -l labs -u deployer -C playbooks/base.yml
  deploy:
    docker:
      - image: circleci/python:3
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - pip-packages-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Run the base playbook against all Droplets
          command: pipenv run ansible-playbook -i digital_ocean.py -l labs -u deployer playbooks/base.yml
  check:
    docker:
      - image: circleci/python:3
    environment:
      - ANSIBLE_FORCE_COLOR: "True"
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-packages-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Run the checks against all Droplets
          command: pipenv run ansible-playbook -i digital_ocean.py -l labs -u deployer playbooks/check.yml
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - check
