# failsafe to help ensure that you don't get locked out of the machine
- name: Fail if no users are specified
  fail:
    msg: No users are specified
  when: not users

- name: Harden SSH configuration
  include_role:
    name: dev-sec.ssh-hardening
  vars:
    # just to be safe
    ssh_max_auth_retries: 100
    ssh_print_motd: true

- name: Restart SSH daemon
  meta: flush_handlers

- name: Unlock users
  include_tasks: unlock.yml
  loop: "{{ ssh_users }}"
