- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin no
  when: disable_root
  notify: Restart SSH
- name: Disallow SSH authentication with password
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication no
  notify: Restart SSH

# failsafe to help ensure that you don't get locked out of the machine
- name: Fail if no users are specified
  fail:
    msg: No users are specified
  when: not users
- name: Only allow specified users to SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^AllowUsers
    line: AllowUsers deployer {{ 'vagrant ' if ansible_user == 'vagrant' else '' }}{{ users|join(' ') }}
  when: disable_root
  notify: Restart SSH
