---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    disable_root: false

    users:
      - afeld
      - allthesignals
      - andycochran
      - chriswhong
    former_users: []

  roles:
    - role: andrewsomething.do-agent
    - role: jnv.unattended-upgrades
  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
  tasks:
    - name: User management
      include_tasks: ../tasks/users.yml
    - name: SSH configuration
      include_tasks: ../tasks/ssh.yml

    - name: Check if machine requires reboot
      stat:
        # https://askubuntu.com/a/171
        path: /var/run/reboot-required
      register: stat_result
    - name: Alert if reboot required
      fail:
        msg: Reboot required
      when: stat_result.stat.exists
