---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Check if machine requires reboot
      stat:
        # https://askubuntu.com/a/171
        path: /var/run/reboot-required
      register: stat_result
    - name: Alert if reboot required
      fail:
        msg: Reboot required. When you can handle downtime, SSH in and run 'sudo shutdown -r now'.
      when: stat_result.stat.exists
