---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: python3
    checkout_dir: /srv/checkout
  roles:
    - role: common
    - role: docker
  tasks:
    - name: Clone repository
      git:
        repo: https://github.com/NYCPlanning/labs-geosearch-dockerfiles.git
        dest: "{{ checkout_dir }}"

    - name: Install Pip
      apt:
        name: python3-pip
        update_cache: true
        state: latest
    - name: Upgrade Pip
      pip:
        name: pip
        state: latest
    - name: Install Docker depdendencies
      pip:
        name: docker-compose
        state: latest

    - name: Start Elasticsearch
      docker_service:
        project_src: "{{ checkout_dir }}"
        services:
          - elasticsearch
        build: true
