---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: python3
    checkout_dir: /srv/checkout
  # roles:
  #   - role: common
  #   - role: docker
  tasks:
    - name: Install packages
      apt:
        name:
          - docker-ce
          - python3-pip
        update_cache: true
        state: latest

    - name: Upgrade Pip
      pip:
        name: pip
        state: latest
    - name: Install Docker depdendencies
      pip:
        name: docker-compose
        state: latest

    # - name: Clone repository
    #   git:
    #     repo: https://github.com/NYCPlanning/labs-geosearch-dockerfiles.git
    #     dest: "{{ checkout_dir }}"
    - name: Copy repository
      synchronize:
        src: ../../labs-geosearch-dockerfiles
        dest: "{{ checkout_dir }}"

    - name: Start Elasticsearch
      docker_service:
        project_src: "{{ checkout_dir }}"
        services:
          - elasticsearch
        build: true

    - name: Create the schema
      command: docker-compose run --rm schema npm run create_index
      args:
        chdir: "{{ checkout_dir }}"
      # TODO conditional?

    - name: Start API
      docker_service:
        project_src: "{{ checkout_dir }}"
        services:
          - api
        build: true
