---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: python3
    checkout_dir: /srv/checkout
    repo_dir: "{{ checkout_dir }}/labs-geosearch-dockerfiles"
    run_import: false
  roles:
    - role: common
    - role: docker
  tasks:
    - name: Install packages
      apt:
        name:
          - docker-ce
          - python3-pip
        update_cache: true
        state: latest

    - name: Upgrade Pip
      pip:
        name: pip
        state: latest
    - name: Install Docker depdendencies
      pip:
        name: docker-compose
        state: latest

    # - name: Clone repository
    #   git:
    #     repo: https://github.com/NYCPlanning/labs-geosearch-dockerfiles.git
    #     dest: "{{ checkout_dir }}"
    # uncomment for local development
    - name: Copy repository
      synchronize:
        src: ../../labs-geosearch-dockerfiles
        dest: "{{ checkout_dir }}"

    - name: Start the server
      command: ./build.sh
      args:
        chdir: "{{ repo_dir }}"
      environment:
        DATA_DIR: /srv
      # TODO conditional?

    - name: Run the import
      command: ./import-pad.sh
      args:
        chdir: "{{ repo_dir }}"
      # environment:
      #   SLACK_WEBHOOK_URL: ...
      when: run_import
